from config import ADMIN_LEVELS

from database import (
    get_security_events,
)


# =========================================================
# ADMIN LEVEL ORDER
# =========================================================

LEVEL_ORDER = {
    "BOOTH": 1,
    "ZONAL": 2,
    "DEPUTY": 3,
    "CENTRAL": 4,
}


# =========================================================
# GET ALERTS VISIBLE TO A ROLE
# =========================================================

def get_visible_security_alerts(
    viewer_role,
    limit=50,
):
    """
    Return security alerts that should be visible to the
    currently logged-in administrative level.

    A level can see:
        - alerts from itself
        - alerts from lower administrative levels

    Higher levels therefore receive alerts generated by
    lower levels.
    """

    viewer_role = (
        viewer_role
        .strip()
        .upper()
    )

    if viewer_role not in ADMIN_LEVELS:

        raise ValueError(
            f"Unsupported administrative level: {viewer_role}"
        )

    viewer_rank = LEVEL_ORDER[
        viewer_role
    ]

    events = get_security_events(
        limit=limit
    )

    visible = []

    for event in events:

        (
            event_id,
            source_level,
            event_type,
            severity,
            details,
            timestamp,
            acknowledged,
        ) = event

        source_rank = LEVEL_ORDER.get(
            source_level,
            0
        )

        # -------------------------------------------------
        # ONLY SHOW EVENTS FROM THIS LEVEL OR BELOW
        # -------------------------------------------------

        if source_rank <= viewer_rank:

            visible.append({
                "event_id": event_id,
                "source_level": source_level,
                "event_type": event_type,
                "severity": severity,
                "details": details,
                "timestamp": timestamp,
                "acknowledged": bool(
                    acknowledged
                ),
            })

    return visible


# =========================================================
# GET UNACKNOWLEDGED ALERT COUNT
# =========================================================

def get_unacknowledged_alert_count(
    viewer_role
):

    alerts = get_visible_security_alerts(
        viewer_role
    )

    return sum(
        1
        for alert in alerts
        if not alert["acknowledged"]
    )


# =========================================================
# GET HIGH-SEVERITY ALERTS
# =========================================================

def get_high_severity_alerts(
    viewer_role,
    limit=20,
):

    alerts = get_visible_security_alerts(
        viewer_role,
        limit=limit
    )

    return [
        alert
        for alert in alerts
        if alert["severity"].upper()
        in (
            "HIGH",
            "CRITICAL",
        )
    ]